// const initialState = [
//   {
//     id: 1,
//     topic: 'Redux',
//     experience: 'Fall in love with Redux',
//     hours_taken: 3,
//     completed: true,
//     user: {
//       id: 1,
//       username: 'Rex',
//       fullname: 'Htet Naing',
//       email: 'rex@soul.com',
//       city: 'Yangon',
//       bio: null,
//       birthdate: '2000-03-18',
//       image: null,
//       role: 'learner',
//     },
//     technology: {
//       id: 1,
//       name: 'React',
//     },
//   },
//   {
//     id: 2,
//     topic: 'Ruby On Rails',
//     experience: null,
//     hours_taken: 0,
//     completed: true,
//     user: {
//       id: 2,
//       username: 'SaSa',
//       fullname: 'Sa Aung Htet Nyein',
//       email: 'sasa@sasa.com',
//       city: 'Yangon',
//       bio: null,
//       birthdate: '1999-11-07',
//       image: null,
//       role: 'learner',
//     },
//     technology: {
//       id: 2,
//       name: 'Ruby',
//     },
//   },
// ];

// const studies = [{
//   id: 1,
//   topic: 'State Management',
//   experience: null,
//   completed: true,
//   hours_taken: 0,
//   user_id: 1,
//   technology_id: 1,
// }, {
//   id: 2,
//   topic: 'Ruby jajaja',
//   experience: null,
//   completed: true,
//   hours_taken: 0,
//   user_id: 1,
//   technology_id: 1,
// }];

// const initialState = [
//   {
//     id: 1,
//     username: 'Rex',
//     fullname: 'Htet Naing',
//     image: 'https://static.zerochan.net/Dante.full.2952055.jpg',
//     bio: "I'm a web developer",
//     city: 'Yangon',
//     birthdate: '1990-01-01',
//     phone: '+959443112251',
//     role: 'admin',
//     email: 'htetnaing0814@gmail.com',
//     password: 'P@ssw0rd',
//     github: 'https://github.com/rex-9',
//     linkedin: 'https://www.linkedin.com/in/rex-9',
//   },
//   {
//     id: 2,
//     username: 'Jerry',
//     fullname: 'Sai La Min Oak',
//     image: null,
//     bio: null,
//     city: 'Mandalay',
//     birthdate: '1990-01-01',
//     phone: '+959443112251',
//     role: 'learner',
//     email: 'jerry@gmail.com',
//     password: 'P@ssw0rd',
//     github: null,
//     linkedin: null,
//   },
//   {
//     id: 3,
//     username: 'SwanHtet18',
//     fullname: 'Swan Htet',
//     image: 'https://static.zerochan.net/Dante.full.2952055.jpg',
//     bio: 'I am UI designer',
//     city: 'Pyin Oo Lwin',
//     birthdate: '1990-01-01',
//     phone: '+959443112251',
//     role: 'learner',
//     email: 'SwanHtet18@gmail.com',
//     password: 'P@ssw0rd',
//     github: 'https://github.com/Swanhtet18',
//     linkedin: 'https://www.linkedin.com/in/Swanhtet18',
//   },
// ];

// export default studies;
